---
title: Jerin Joseph J A 200101074 DSA Individual Assignment Submitted to Prof (Dr) Sridhar Vaithianathan, Associate
  Professor (Analytics), IMT Hyderabad
author: "Jerin Joseph J A"
date: "12/19/2020"
output:
  word_document: default
  pdf_document: default
---
```{r}

#TABLE OF CONTENTS

#Creating Variables & Simple Calculations
#Data Types & Class of Objects
#Arrays & Concatenation
#Listing & Deleting variables
#Vector
#sequencing using :(colon)
#Matrix
#nchar
#Vectors naming and accessing individual elements in vectors using []
#Dataframe
#Dimensions of Dataframe and Head and Tail in a Dataframe
#Accessing specific rows and columns in Dataframe
#Matrix Creation
#Arrays and basic operations in it
#Lists
#Statistics in R
#Mean, Median, Mode, Variance, weighted mean, finding missing values
#Summary statistics in R
#Co-variance and correlation begins
#Hypothesis testing in R t-test







#---
```

```{r}
# Creating variables & Simple Calculations
a = 10
a
b = 5
b
# Finding class of object
a = 10
class(a)
a = "Hello"
class(a)
a = TRUE
class(a)
a = FALSE
class (a)

# Simple Math in R
x = 10
y = 15
x+y
x-y
x*y
x/y
sqrt(x)
x^y
exp(x)
log(x, base=exp(1))
log10(x)
help("log") #Help in R for functions
factorial(x)
cos(x)
abs(x)
```

```{r}
# DATA TYPES in R are Nominal, Ordinal, Interval and Ratio

x = 10
class(x)
# Numeric 
#This data type is for Integer and Decimal (i.e.) Integer (Whole Number) and Numeric (Float - Decimal)
i = 5L # L - Specifies the object is Integer 
class(i) #to check if object is which class
is.integer(i) #to check if object is integer
is.numeric(x) #tocheck of object is numeric

# Character
#This data type is for Categorical Variable - Words/String (Nominal), Classification (Gender - Male , Female)
s = "Keshav"
class(s)
# Levels of Classification - Factor --- Involves levels.(Ordinal) 
# Eg: Edu Quali - X, XII, Graduation, Post Graduation (4 Levels)

# Logical
#It has 2 - TRUE & FALSE where the value of True in R is 1 and False is 0
TRUE * 5
FALSE * 5

K = TRUE
class(K)
is.logical(K)

# Date - Starting Date (1970) - Numeric Value.
#In R date start from 1 Jan 1970
#Date - mm/dd/yyyy this format in R
#POSIXct - Combines Date & Time and gives no. of seconds from 1 jan 1970 to a particular date and time

date1 = as.Date("2012-06-28")
#as.Date() - command for dates
date1
class (date1)
as.numeric(date1)

#POSIXct - Date and Time
date2 = as.POSIXct("2012-06-28 17:42")
date2
class(date2)
as.numeric(date2)
```

```{r}
# Working Directory
getwd()
a=2
a
```

```{r}
# Arithmetic functions in R

# Division
divider = function(x,y) {
  result = x/y
  print(result)
}
divider(50,25)
divider (100,25)

# Multiplication
multiply = function(a,b){
  result = a * b
  print (result)
}
multiply(23,25)
multiply (19,20)


# Variables Names are Case sensitive
A=10
a=24

# CONCATENATION AND ARRAYS
f <- c(1,2,3,4,5)
f = c(1,2,3,4,5)
f
f+10

d = f / 2
d

f+d

f = c(1,2,3,4,5)
  
# Listing and Deleting Objects (Variables)
ls() #Listing formula
rm (a) #deletes value of object
rm (list = ls())
```

```{r}
# Vector - R is called as Vectorized language.
#Vector can only have a collection of same type of elements
# Creating Vectors 
#Use 'c' (i.e. combine) to create vectors
x = c(1,2,3,4,5,6,7,8,9,10)
x

# Vector Operations
x*3 #multiplies each element by 3 automatically
x+2
x-3
x/4
x^2
sqrt(x)

# Colon (:) Sequencing operations
#Creates sequence of Numbers in either direction
1:10 #(: - Through)
10:1
-2:3
5:-7

# Creating two vectors and performing calculations
x = 1:10
y = -5:4
x + y #Add
x-y #subtract
x*y #multiply
x/y #divide
x^y #exponent
# Length of vector
length(x)
length(y)
#For unequal length vectors, shorter vector gets recycled!
x+c(1,2)
#If longer vector is not a "multiple" of shorter vector, a warning is given
x+c (1,2,3)
# Comparing different vectors
x <= 5
x<y
# Vector Comparison - "any" and "all"
x = 10:1
y = -4:5
any(x<y)
all(x<y)

# nchar
#The "nchar" function also acts on each element of vector. It calculates no. of elements in particular object
q = c("Hockey","Football","Baseball","Curlin","Rugby","Lacrosse",
      "Basketball","Tennis","Cricket","Soccer")
q
nchar(q)
nchar(y)

?nchar()

# Accessing "individual elements" in vector is done using square brackets []
x[1]
x[1:2]
x[c(1:5,9)]

# Naming Vector!
c(One = "a", Two = "y", Last = "r") # Name-Value pair
#Vector can be named after creating vector
w = 1:3
names(w) = c("a","b","c")
w
# Creating a Dataframe from vectors

x = 10:1
y = -4:5
q = c("Hockey","Football","Baseball","Curlin","Rugby","Lacrosse",
      "Basketball","Tennis","Cricket","Soccer")
theDF = data.frame(x,y,q) #this would create a 10x3 data.frame with x, y and q as variable names
theDF

# Assigning Names
theDF = data.frame (First=x, Second =y, Sport = q)
theDF

# Checking the dimensions of the DF.
nrow(theDF)
ncol(theDF)
dim(theDF)
names (theDF)
names(theDF)[3]
rownames(theDF)

# Head and Tail
head(theDF)
head(theDF, n=7)
tail(theDF)

class(theDF)

# Accessing Individual Column using $
theDF$Sport #gives the third column named Sport

# Accessing Specific row and column
theDF[3,2] #3rd row and 2nd Column
theDF[3,2:3] #3rd Row and column 2 thru 3
theDF[c(3,5), 2]#Row 3&5 from Column 2; 
#since only one column was selected, it was returned as vector and hence no column names in output.

# Rows 3&5 and Columns 2 through 3
theDF[c(3,5), 2:3]

theDF[ ,3] #Access all Rows for column 3
theDF[ , 2:3]

theDF[2,]#Access all columns for Row 2
theDF[2:4,]
theDF[ , c("First", "Sport")]#access using Column Names

# Factor Vectors - Ordinal data [Ordered Categorical]
#Factors are important concept in R, esp. when building models

q2 = c(q,"Hockey","Lacrosse","Hockey","Water Polo","Hockey","Lacrosse")
q2
class(q2)
as.numeric(q2)

class(q2)
# Converting "q2" to factor!
q2_F = as.factor(q2)
q2_F #notice the "Levels" info in the output!
#11 Levels - 10 Distinct Names from "q" and one (Water polo) from "q2" 
#The "levels" of a factor are the unique values of that factor variable.
#Technically R is giving "unique integer" to each distinct names, See below
as.numeric(q2_F)#In the O/P --> Notice "6" = "Hockey"

# Ordered Levels and Un-ordered Levels
#Factors can reduce the size of the variable because they store only unique values
factor(x=c("High School","College","Masters","Doctrate"),
       levels = c("High School","College","Masters","Doctrate"),
       ordered = TRUE)
#Missing data plays a crucial role in computing and Statistics
#R has two types of missing data - NA and NULL
#while they are similar, but they behave differently and hence needs attention!

# NA - Gives Missing value in a Vector
z = c(1,2,NA,8,3,NA,3)
z = c(1,2,NA,8,3,NA,3)
z
#"is.na" tests each element of a vector for missingness
is.na(z)

#Another example
z_char = c("Hockey", NA ,"Cricket")
z_char
is.na(z_char)

# NULL - Absence of anything. 
#It is not exactly missingness, but nothingness
#Functions can sometimes return NULL and their arguments can be NULL.
#Important difference is, NULL is atomical and cannot exist within a vector. If used, it disappears
z= c(1,NULL,3)
z
x = c(1,NA,3)
x 
#Notice, here the "NULL" didnot get stored in "z", infact "z" has only length of 2
length(z)
length(x)

# Assigning NULL and checking
d = NULL
is.null(d)
```

```{r}
# Data Structures in R


# Data Frames(DF) - Most useful features of R & also cited reason for R's ease of use.
#In dataframe, each column is actually a vector, each of which has same length.
#Each column can hold different type of data.
#Also within each column, each element must be of same type, like vectors.

# Creating a Dataframe from vectors

x = 10:1
y = -4:5
q = c("Hockey","Football","Baseball","Curlin","Rugby","Lacrosse",
      "Basketball","Tennis","Cricket","Soccer")
theDF = data.frame(x,y,q) #this would create a 10x3 data.frame with x, y and q as variable names
theDF
str(theDF)#Very important - Str - Structure
q = as.factor(q)

# Assigning Names
theDF = data.frame (First=x, Second =y, Sport = q)
theDF


# Checking the dimensions of the DF.
nrow(theDF)
ncol(theDF)
dim(theDF)
names (theDF)
names(theDF)[3]
rownames(theDF)

# Head and Tail
#Head gives first half of Dataframe
#Tail gives second half of dataframe
head(theDF)#First 6 rows with all columns
head(theDF, n=10)
tail(theDF)#last six rows with all columns
# Checking class of dataframe
class(theDF)

# Accessing Individual Column using $ in dataframe
theDF$Sport #gives the third column named Sport

# Accessing Specific row and column in dataframe
theDF[3,2] #3rd row and 2nd Column
theDF[3,2:3] #3rd Row and column 2 through 3
theDF[c(3,5), 2]#Row 3&5 from Column 2; 
#since only one column was selected, it was returned as vector and hence no column names in output.

#Rows 3&5 and Columns 2 through 3
theDF[c(3,5), 2:3]

theDF[ ,3] #Access all Rows for column 3
theDF[ , 2:3]

theDF[2,]#Access all columns for Row 2
theDF[2:4,]
theDF[ , c("First", "Sport")]#access using Column Names

theDF[ ,"Sport"]#Access specific Column
class(theDF[ ,"Sport"])

theDF["Sport"]#This returns the one column data.frame
class(theDF["Sport"]) #Data.Frame

theDF[["Sport"]]#To access Specific column using Double Square Brackets
class(theDF[["Sport"]]) #Factor

theDF[ ,"Sport", drop = FALSE]#Use "Drop=FALSE" to get data.fame with single square bracket.
class(theDF[ ,"Sport", drop = FALSE]) #data.frame

theDF[ ,3, drop = FALSE]
class(theDF[ ,3, drop = FALSE]) #data.frame

# To see how factor is stored in data.frame
newFactor = factor(c("Pennsylvania","New York","New Jersey","New York","Tennessee","Massachusetts","Pennsylvania","New York"))
newFactor
#model.matrix(~newFactor -1)
#? model.matrix()
#A matrix (plural matrices) is a rectangular array or table of numbers, symbols, or expressions, arranged in rows and columns.(i.e.) 2-Dimensional Array
#Similar to data.frame(RxC) and also similar to Vector

# Matrix - Element by element operations are possible

A = matrix(1:10, nrow=5)#Create a 5x2 matrix
B = matrix(21:30, nrow=5)#Create another 5x2 matrix 
C = matrix (21:40, nrow=2)#Create another 2x10 matrix

A
B
C

nrow(A)
ncol(A)
dim(A)

# Vector Addition
A+B

# Vector Multiplication
A
B
A*B  #A = 5x2 and B = 5x2

#See if the elements are equal
A == B

#Matrix Multiplication(MM. A is 5x2. B is 5x2. B-transpose is 2x5
A %*% t(B)

# Naming the Columns and Rows 
colnames(A)
rownames(A)
colnames(A)= c("Left","Right")
rownames(A)= c("1st","2nd","3rd","4th","5th")
colnames(B)
rownames(B)
colnames(B)= c("First","Second")
rownames(B)= c("One","Two","Three","Four","Five")
colnames(C)
rownames(C)

colnames(C) = LETTERS [1:10]
rownames(C) = c("Top", "Bottom")

#Matrix Multiplication. A is 5x2 and C is 2x10
dim(A)
dim(C)
t(A)
A %*% C
# Arrays - An array is essentially a multidimensional vector.
#It must all be of the same type and individual elements are accessed using Square Brackets.
#First element is Row(R) Index, Second Element is Column(C) Index and the remaining elements are for Outer Dimensions (OD).

theArray = array(1:12, dim=c(2,3,2))#Total Elements = R x C x OD
theArray
theArray [1, ,]#Accessing all elements from Row 1, all columns, all outer dimensions & build C x OD (R x C)
theArray[1, ,1]#Accessing all elements from Row 1, all columns, first outer dimension 
theArray[, ,1]#Accessing all rows, all columns, first outer dimension

# Array with Four Outer Dimensions (OD)
theArray_4D = array(1:32, dim=c(2,4,4))
theArray_4D
theArray_4D [1, ,]
theArray_4D[1, ,1]
theArray[, ,1]

# Lists - Stores any number of items of any type.
#List can contain all numeric or character or a mix of the two or data.frames or recursively other lists.

#Lists are created with the "list" function.
#Each argument in "list" becomes an element of the list.

list(1,2,3)#creates a three element list
list(c(1,2,3))#creates a single element(vector with three elements)
list3 = list(c(1,2,3), 3:7)#create two element list
#first is three elements vector, next is five element vector.
list3
#The same can be written as
(list3 = list(c(1,2,3), 3:7))

# Two Element list
#First element is data.frame and next is 10 element vector
list(theDF, 1:10)#theDF is already created in previous exercise!

# Three element list
list5 = list(theDF, 1:10, list3)
list5

# Naming List (similar to column name in data.frame) 
names(list5)= c("data.frame", "vector","list")
names(list5)
list5
# Naming using "Name-Value" pair
list6 = list(TheDataFrame = theDF, TheVector = 1:10, TheList = list3)
names(list6)
list6

# Creating an empty list
(emptylist = vector(mode="list", length =4))

# Accessing individual element of a list - Double Square Brackets
#specify either element number or name
list5[[1]]
list5[["data.frame"]]
list5[[1]]$Sport
list5[[1]][,"Second"]
list5[[1]][,"Second", drop = FALSE]

# LENGTH OF LIST
length(list5)
names(list5)
list5
#Its time that we load data in R.
#Most common way to get data is reading comma separated values(CSV)

# Reading CSVs
theUrl = "http://www.jaredlander.com/data/Tomato%20First.csv"
# visit https://www.jaredlander.com/data/ for other Datasets
tomato = read.table(file=theUrl, header=TRUE, sep =",")
head(tomato)

#It might be tempting to use read.csv but that is more trouble than it is worth, and all it does is call read.table with some arguments preset.

#Sometimes CSVs(or tab delimited files) are poorly built, where the cell separator has been used inside a cell.
#In this case read.csv2(or read.delim2)should be used instead of read.table.

#Reading Excel Data - Not worth the Effort.
#Unfortunately, it is difficult to read Excel data into R - Requires additional packages to be installed.
#Convert into CSV and read.

#Read data from anywhere in the Disk/Computer
#myData = read.csv(file.choose()) # No working directory setup is needed.
#Built-in datasets in R
data()#List of built-in Datasets in R

#Loading
data(mtcars)
#Print the first 6 rows
head(mtcars, 6)

#Beginning of statistics, Multiple linear regression
# Basic Statistics - Mean, Variances,Correlations and T-tests

# Generate a random sample of 100 numbers between 1 and 100
x = sample(x=1:100, size = 100, replace = TRUE)
x #the output of "x" is a vector of data

# Simple Arithmetic Mean
mean(x)

#Calculate Mean when Missing Data is found
y = x #copy x to y
y[sample(x=1:100, size = 20, replace = FALSE)] = NA
y

mean(y)#Will give NA
#Remove missing value(s)and calculate mean
mean(y, na.rm=TRUE) #Now, it will give the mean value

# Weighted Mean
Grades = c(95,72,87,66)
Weights = c(1/2, 1/4, 1/8, 1/8)
mean(Grades)#Simple Arithmetic mean
weighted.mean(x = Grades, w = Weights)# Weighted Mean

# Variance
var(x)
# Calculating Variance using formula
sum((x-mean(x))^2)/ (length(x)-1)

# Standard Deviation
sqrt(var(x))
sd(x)
sd(y)
sd(y, na.rm=TRUE)

# Other Commonly Used Functions
min(x)
max(x)
median(x)
min(y)
min(y, na.rm=TRUE)

# Summary Statistics
summary(x)
summary(y)

# Quantiles
quantile(x, probs = c(0.25, 0.75)) # Calculate 25th and 75th Quantile
quantile(x, probs = c(0.1,0.25,0.5, 0.75,0.99))

# Correlation and Covariance
install.packages("ggplot2", repos = "http://cran.us.r-project.org")
library(ggplot2)# require(ggplot2)
head(economics)# Built-in dataset in ggplot2 package
cor(economics$pce, economics$psavert) #pce-Personal Consumption Expenditure;psavert -Personal Savings Rate

# To compare correlation for Multiple variables
cor(economics[, c(2,4:6)])
#Display Correlation in Different Format

# Load the "reshape" package
install.packages("reshape2", repos = "http://cran.us.r-project.org")
require(reshape2)
#Also load the Scales package for some extra plotting features
install.packages("scales", repos = "http://cran.us.r-project.org")
library(scales)

econCor = cor(economics [ , c(2,4:6)])
#use "melt()" to change into long format
?melt() #Help on melt function
econMelt = melt(econCor, varnames = c("x" ,"y"), value.name = "Correlation")
#Order it according to correlation
econMelt = econMelt[order(econMelt$Correlation),]
#Display the melted data
econMelt

#Let's Visualize Correlation
#Plot it with ggplot
#Initialize the plot with x and y on the respective axes
ggplot(econMelt,aes (x=x, y=y),geom_tile(aes(fill = Correlation)),scale_fill_gradient2(low = muted("red"), mid = "white", high = "steelblue",guide = guide_colorbar(ticks=FALSE, barheight=10), limit=c(-1,1), theme_minimal(), labs(x= NULL, y=NULL)))

```

```{r}
# Hypothesis testing in R
# T-tests
#Dataset: Tips dependents on...
data(tips, package = "reshape2")
head(tips)
str(tips)

# Gender
unique(tips$sex)
# Day of the week
unique(tips$day)

# One Sample t-test - ONE GROUP [Two Tail. Ho:Mean = 2.5]
t.test(tips$tip, alternative = "two.sided", mu=2.5)

# One Sample t-test - Upper Tail. Ho:Mean LE 2.5
t.test(tips$tip, alternative = "greater", mu=2.5)

# Two Sample T-test - TWO GROUP
t.test(tip ~ sex, data = tips, var.equal = TRUE)

# Paired Two-Sample T-Test 
#Dataset- Heights of Father and Son (Package:UsingR)
install.packages("UsingR", repos = "http://cran.us.r-project.org")
require(UsingR)
head(father.son)

# ANOVA  - Comparing Multiple Groups
#Tip by the Day of the Week
str(tips)
tipAnova = aov(tip ~ day, tips)

```

